[Languages]
0404 = TChinese
0C04 = TChinese
1404 = TChinese

1004 = SChinese
0804 = SChinese

;01 = Arabic
09 = English
0C = French
07 = German
11 = Japanese
;10 = Italian
12 = Korean
19 = Russian
0A = Spanish
;0816 = Portuguese
;13 = Dutch
;0416 = Brazil
;1F = Turkish
;1E = Thai
;05 = Czech
;1B = Slovak
;0E = Hungarian
;06 = Danish
;0B = Finnish
;14 = Norwegian
;1D = Swedish 
;15 = Polish

[Select_Lang]
RootKey = HKEY_LOCAL_MACHINE
SubKey = SOFTWARE\ASUS\AI-SUITE_II
Value = Language
